import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  subsets: ["thai"],
  weight: ["300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.className} ${kanit.className} antialiased`}
      >
        {children}

        <div className="text-center text-gray-800 mt-20 font-bold">
          <hr className="w-2xl mx-auto"/>
          Created by Kritsana Rachasuth
          <br />
          Copyright &copy; 2025
        </div>
      </body>
    </html>
  );
}
